// Mocks generated by Mockito 5.4.6 from annotations
// in chefleet/test/features/auth/widgets/guest_ui_components_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chefleet/core/services/guest_conversion_service.dart' as _i4;
import 'package:chefleet/features/auth/blocs/auth_bloc.dart' as _i2;
import 'package:chefleet/features/auth/blocs/user_profile_bloc.dart' as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileState_1 extends _i1.SmartFake
    implements _i3.UserProfileState {
  _FakeUserProfileState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversionResult_2 extends _i1.SmartFake
    implements _i4.ConversionResult {
  _FakeConversionResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGuestSessionStats_3 extends _i1.SmartFake
    implements _i4.GuestSessionStats {
  _FakeGuestSessionStats_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i2.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_0(this, Invocation.getter(#state)),
          )
          as _i2.AuthState);

  @override
  _i5.Stream<_i2.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i2.AuthState>.empty(),
          )
          as _i5.Stream<_i2.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> updatePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [currentPassword, newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void add(_i2.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i2.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i2.AuthEvent>(
    _i6.EventHandler<E, _i2.AuthState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i6.Transition<_i2.AuthEvent, _i2.AuthState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onChange(_i6.Change<_i2.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserProfileBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileBloc extends _i1.Mock implements _i3.UserProfileBloc {
  MockUserProfileBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserProfileState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeUserProfileState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.UserProfileState);

  @override
  _i5.Stream<_i3.UserProfileState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.UserProfileState>.empty(),
          )
          as _i5.Stream<_i3.UserProfileState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> clearProfile() =>
      (super.noSuchMethod(
            Invocation.method(#clearProfile, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void add(_i3.UserProfileEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.UserProfileEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.UserProfileState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.UserProfileEvent>(
    _i6.EventHandler<E, _i3.UserProfileState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i6.Transition<_i3.UserProfileEvent, _i3.UserProfileState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onChange(_i6.Change<_i3.UserProfileState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GuestConversionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuestConversionService extends _i1.Mock
    implements _i4.GuestConversionService {
  MockGuestConversionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.ConversionResult> convertGuestToRegistered({
    required String? guestId,
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertGuestToRegistered, [], {
              #guestId: guestId,
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue: _i5.Future<_i4.ConversionResult>.value(
              _FakeConversionResult_2(
                this,
                Invocation.method(#convertGuestToRegistered, [], {
                  #guestId: guestId,
                  #email: email,
                  #password: password,
                  #name: name,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.ConversionResult>);

  @override
  _i5.Future<_i4.GuestSessionStats> getGuestSessionStats(String? guestId) =>
      (super.noSuchMethod(
            Invocation.method(#getGuestSessionStats, [guestId]),
            returnValue: _i5.Future<_i4.GuestSessionStats>.value(
              _FakeGuestSessionStats_3(
                this,
                Invocation.method(#getGuestSessionStats, [guestId]),
              ),
            ),
          )
          as _i5.Future<_i4.GuestSessionStats>);

  @override
  bool shouldPromptConversion(_i4.GuestSessionStats? stats) =>
      (super.noSuchMethod(
            Invocation.method(#shouldPromptConversion, [stats]),
            returnValue: false,
          )
          as bool);
}
